### ISSUE TITLE
Can't use virtual list with custom elements

### ISSUE THREAD

**Issue by lgabeskiria** [aurelia/ui-virtualization#42]
Getting errors when using [virtual-repeat] with custom elements

``` javascript
Uncaught (in promise) TypeError: Cannot read property 'localName' of null
    at DefaultStrategy.createTopBufferElement (http://localhost:9000/jspm_packages/npm/aurelia-ui-virtualization@0.4.1/view-strategy.js:94:46)
    at VirtualRepeat.attached (http://localhost:9000/jspm_packages/npm/aurelia-ui-virtualization@0.4.1/virtual-repeat.js:135:42)
    at Controller.attached (http://localhost:9000/jspm_packages/npm/aurelia-templating@1.0.0-beta.1.2.1/aurelia-templating.js:2877:24)
    at View.attached (http://localhost:9000/jspm_packages/npm/aurelia-templating@1.0.0-beta.1.2.1/aurelia-templating.js:1020:24)
    at View.attached (http://localhost:9000/jspm_packages/npm/aurelia-templating@1.0.0-beta.1.2.1/aurelia-templating.js:1025:21)
    at View.attached (http://localhost:9000/jspm_packages/npm/aurelia-templating@1.0.0-beta.1.2.1/aurelia-templating.js:1025:21)
    at View.attached (http://localhost:9000/jspm_packages/npm/aurelia-templating@1.0.0-beta.1.2.1/aurelia-templating.js:1025:21)
    at ViewSlot.attached (http://localhost:9000/jspm_packages/npm/aurelia-templating@1.0.0-beta.1.2.1/aurelia-templating.js:1403:15)
    at View.attached (http://localhost:9000/jspm_packages/npm/aurelia-templating@1.0.0-beta.1.2.1/aurelia-templating.js:1025:21)
    at View.attached (http://localhost:9000/jspm_packages/npm/aurelia-templating@1.0.0-beta.1.2.1/aurelia-templating.js:1025:21)
```

``` html
<my-list>
    <my-list-item virtual-repeat.for="item of items">
        ${$index} ${item}
    </my-list-item>
</my-list>
```

``` javascript
export class MyVirtualList {
    items = ['Foo', 'Bar', 'Baz'];
}
```

**Comment by martingust** [comment]
This is fixed in master and will go out in next release. https://github.com/aurelia/ui-virtualization/commit/1bc51a35271819b426a4d6650695006189933d09#diff-adfac5d6d19a901dc28a013797bd8541L15
