### ISSUE TITLE
Error: Could not calculate item height

### ISSUE THREAD

**Issue by alexsurg** [aurelia/ui-virtualization#66]
Hi,
After the latest update of the framework packages virtual repeat stoped working.
My code is very simple:

```
<div style="overflow: scroll; height: 340px;">
          <div style="height:27px; line-height:27px;" virtual-repeat.for="item of items">
                  <label>${item.Description}</label>
          </div>
</div>
```

When this code is executes only the first item of the array is rendered and than i get the following exception:

```
loggingServices.js:40 ERROR [client] Unhandled promise rejection: Error: Could not calculate item height
    at VirtualRepeat._calcInitialHeights (http://localhost:32433/jspm_packages/npm/aurelia-ui-virtualization@0.4.6/virtual-repeat.js:416:15)
    at VirtualRepeat.itemsChanged (http://localhost:32433/jspm_packages/npm/aurelia-ui-virtualization@0.4.6/virtual-repeat.js:208:12)
    at VirtualRepeat.attached (http://localhost:32433/jspm_packages/npm/aurelia-ui-virtualization@0.4.6/virtual-repeat.js:140:12)
    at Controller.attached (http://localhost:32433/jspm_packages/npm/aurelia-templating@1.0.0-beta.3.0.6/aurelia-templating.js:3409:24)
    at View.attached (http://localhost:32433/jspm_packages/npm/aurelia-templating@1.0.0-beta.3.0.6/aurelia-templating.js:1533:24)
    at ViewSlot.attached (http://localhost:32433/jspm_packages/npm/aurelia-templating@1.0.0-beta.3.0.6/aurelia-templating.js:1887:15)
    at View.attached (http://localhost:32433/jspm_packages/npm/aurelia-templating@1.0.0-beta.3.0.6/aurelia-templating.js:1538:21)
    at ViewSlot.add (http://localhost:32433/jspm_packages/npm/aurelia-templating@1.0.0-beta.3.0.6/aurelia-templating.js:1696:14)
    at eval (http://localhost:32433/jspm_packages/npm/aurelia-templating-router@1.0.0-beta.2.0.3/router-view.js:202:29)
```

Can you please help me with this issue.

Thanks,
Alex

**Comment by martingust** [comment]
@alexsurg It looks like you are on an old version of UI-Virtualization (0.4.6), can you try with latest (0.5.2) and see if that makes any difference?

**Comment by alexsurg** [comment]
Great, thanks.
The update to the latest version fixed it.
